name: Delete deployed resources
on:
  pull_request:
    types: ['closed']
jobs:
  main:
    permissions:
      id-token: 'write'
    runs-on: ubuntu-latest
    env:
      GCLOUD_PROJECT_ID: '（プロジェクトID）'
      GCLOUD_DNS_ZONE: '（DNSゾーン名）'
      GCLOUD_DNS_DOMAIN: '（ドメイン）'
      GCLOUD_WORKLOAD_IDENTITY: '（Workload Identity 連携）'
      GCLOUD_REGION: 'asia-northeast1'
    steps:
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v5

    - name: Set DNS
      run: | 
        echo 'TARGET_DOMAIN=${{ steps.branch-name.outputs.current_branch }}.run.${{ env.GCLOUD_DNS_DOMAIN }}' >> $GITHUB_ENV

    - id: auth
      name: Set up GoogleCloud Authorization
      uses: google-github-actions/auth@v0
      with:
        token_format: 'access_token'
        workload_identity_provider: ${{ env.GCLOUD_WORKLOAD_IDENTITY }}
        service_account: 'github-actions@${{ env.GCLOUD_PROJECT_ID }}.iam.gserviceaccount.com'
        access_token_lifetime: '300s'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0

    - id: mapping
      name: Get domain-mapping configure
      run: |
        yes | gcloud components install beta
        result=$(gcloud beta run domain-mappings describe --domain=${{ env.TARGET_DOMAIN }} --format=json --region=${{ env.GCLOUD_REGION }} | jq -c '.status.resourceRecords[0]')
        echo "::set-output name=mapping::$result"

    - name: Delete domain-mapping
      run: |
        gcloud beta run domain-mappings delete --domain=${{ env.TARGET_DOMAIN }} --region=${{ env.GCLOUD_REGION }}

    - name: Delete cloud run
      run: |
        yes | gcloud run services delete ${{ steps.branch-name.outputs.current_branch }} --region=${{ env.GCLOUD_REGION }}

    - name: Delete DNS record
      if: ${{ github.event.action != 'synchronize' }}
      run: |
        gcloud dns record-sets transaction start --zone=${{ env.GCLOUD_DNS_ZONE }} 
        gcloud dns record-sets transaction remove ${{ fromJSON(steps.mapping.outputs.mapping).rrdata }} --name='${{ fromJSON(steps.mapping.outputs.mapping).name }}.${{ env.GCLOUD_DNS_DOMAIN }}.' --ttl=60 --type=${{ fromJSON(steps.mapping.outputs.mapping).type }} --zone=${{ env.GCLOUD_DNS_ZONE }} 
        gcloud dns record-sets transaction execute --zone=${{ env.GCLOUD_DNS_ZONE }}