apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-actions-book-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-actions-book
  template:
    metadata:
      labels:
        app: github-actions-book
    spec:
      containers:
        - name: github-actions-book-app
          image: DEPLOY_IMAGE
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 0.25
              memory: 512Mi
          ports:
          - containerPort: 8080
          env:
          - name: PORT
            value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: github-actions-book-service
spec:
  type: LoadBalancer
  selector:
    app: github-actions-book
  ports:
  - port: 80
    targetPort: 8080